### ISSUE TITLE
pull to fresh: css position fixed not working in children elements

### ISSUE THREAD

**Issue by Damienlu** [thmsgbrt/react-simple-pull-to-refresh#21]
![image](https://user-images.githubusercontent.com/21216112/108944316-74feea80-7695-11eb-954f-938f46588b72.png)

The class ptr__children will add style transform: translate(0,0) while the element is not pulling.
And it makes css position: fixed not working in children.
Could it fix to transform: none; when we stop pulling?

**Comment by thmsgbrt** [comment]
Hi Damienlu,

I'm not sure to understand the behavior you are looking for.
Even if we were to do so, the element that is in fixed position will start moving anyway, the moment ptr is being pulled.

Can you give a bit more context?

**Comment by kevinchanyuanhui** [comment]
i get the same problem ,  

`childrenRef.current.style.transform = "translate(0px, 0px)";` 
will make  fixed style not work in children (just like nav-bar),

`childrenRef.current.style.transform = "none";` can resolve

**Comment by d-s-x** [comment]
> i think change marginTop like `childrenRef.current.style.marginTop= xxx;` will be better

`transform: translate` is GPU accelerated (usually) and requires no reflow

**Comment by alvarocasta** [comment]
same issue here. Children with position fixed will not maintain the position after swiping down for the first time.
This is due to `translate(0px, 0px)` is set to `.ptr__children` container on the first swipe.
I have tried [this fork](https://github.com/jakejdavis/react-simple-pull-to-refresh) from @Jakejdavis and it works perfectly now 👍 
I suggest merging it into the library.

**Comment by thmsgbrt** [comment]
Hello guys, apologies for the delay.
I'm not actively maintaining this library and somehow missed this issue and the addressed fix...
I'm gonna give it a look and merge it this weekend!
